import StyledComponentsRegistry from "./registry";

export const metadata = {
	title: "Sethe Contabilidade",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='pt-br'>
			<body>
				<StyledComponentsRegistry>{children}</StyledComponentsRegistry>
			</body>
		</html>
	);
}
